# Generated by Django 4.2.5 on 2023-11-30 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bank_app.district'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(limit_choices_to={'district': models.F('district')}, on_delete=django.db.models.deletion.CASCADE, related_name='customers_by_branch', to='bank_app.branch'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_by_district', to='bank_app.district'),
        ),
    ]
