# Generated by Django 4.2.5 on 2023-11-30 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_remove_customer_branch_remove_customer_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.district')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(default=1, limit_choices_to={'district': models.F('district')}, on_delete=django.db.models.deletion.CASCADE, related_name='customers_by_branch', to='bank_app.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='district',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='customers_by_district', to='bank_app.district'),
            preserve_default=False,
        ),
    ]
