# Generated by Django 4.2.5 on 2023-11-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_district_branch_customer_branch_customer_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='district',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
