# Generated by Django 4.2.5 on 2023-11-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0006_district_branch_customer_branch_customer_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
